"""
State definitions for the multi-step analysis workflow.

This module defines the state structure for the iterative analysis process
that includes planning, execution, and synthesis phases.
"""

from __future__ import annotations

from typing import Annotated, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AnalysisPlan(TypedDict):
    """Structured analysis plan generated by the Planner."""

    steps: list[dict]
    """
    List of analysis steps, each containing:
    - step_number: int
    - description: str (e.g., "Analyze monthly revenue trend")
    - sql_needed: bool
    - chart_type: str (e.g., "line", "bar", "scatter")
    """

    user_request: str
    """Original user request that triggered the analysis."""

    approved: bool
    """Whether the user has approved this plan."""

    user_edits: str | None
    """Any modifications requested by the user."""


class AnalysisStepResult(TypedDict):
    """Results from executing a single analysis step."""

    step_number: int
    """Which step this result corresponds to."""

    sql_query: str | None
    """SQL query that was executed."""

    data_summary: dict | None
    """Summary of the data retrieved (row count, columns, etc.)."""

    chart_data: dict | None
    """Data formatted for visualization."""

    chart_image_path: str | None
    """Path to the generated chart image."""

    insights: str
    """Vision model's analysis of the chart/data."""


class AnalysisState(TypedDict):
    """Complete state for the multi-step analysis workflow."""

    messages: Annotated[list[BaseMessage], add_messages]
    """Conversation history."""

    user_request: str
    """Original user question/request."""

    schema_info: dict | None
    """
    PostgreSQL schema information:
    - tables: list of table names
    - columns: dict mapping table name to list of columns
    """

    plan: AnalysisPlan | None
    """The analysis plan (pending or approved)."""

    current_step: int
    """Current step being executed (1-indexed)."""

    step_results: list[AnalysisStepResult]
    """Results from completed analysis steps."""

    final_summary: str | None
    """Executive summary synthesized from all step insights."""

    workflow_status: str
    """
    Current workflow status:
    - "planning" - generating the analysis plan
    - "awaiting_approval" - plan ready for user review
    - "executing" - running analysis steps
    - "synthesizing" - generating final summary
    - "completed" - workflow finished
    """
